title: Lixuan (Selina) Wei
page-top-title: Lixuan (Selina) Wei
top-section-bg-text: Efficient · Fair · Reliable AI
home-subtitle: Lixuan (Selina) Wei | Computational Science & ML
copyright-text: '&copy; Lixuan (Selina) Wei 2025. All Rights Reserved.'
